python undirected_prediction_builder_distant.py binds/binds_hidden.txt binds/binds_hidden_linear.txt binds/binds_hidden_hybrid.txt binds/binds_hidden_noisy_or.txt

python prediction_combiner_labelled.py binds/binds_hidden_noisy_or.txt binds/binds_hidden_noisy_or_pr.txt

python prediction_combiner_labelled.py binds/binds_hidden_hybrid.txt binds/binds_hidden_hybrid_pr.txt


python undirected_prediction_builder_distant.py cleaves/cleaves_hidden.txt cleaves/cleaves_hidden_linear.txt cleaves/cleaves_hidden_hybrid.txt cleaves/cleaves_hidden_noisy_or.txt

python prediction_combiner_labelled.py cleaves/cleaves_hidden_noisy_or.txt cleaves/cleaves_hidden_noisy_or_pr.txt

python prediction_combiner_labelled.py cleaves/cleaves_hidden_hybrid.txt cleaves/cleaves_hidden_hybrid_pr.txt


python undirected_prediction_builder_distant.py colocalizes/colocalizes_hidden.txt colocalizes/colocalizes_hidden_linear.txt colocalizes/colocalizes_hidden_hybrid.txt colocalizes/colocalizes_hidden_noisy_or.txt

python prediction_combiner_labelled.py colocalizes/colocalizes_hidden_noisy_or.txt colocalizes/colocalizes_hidden_noisy_or_pr.txt

python prediction_combiner_labelled.py colocalizes/colocalizes_hidden_hybrid.txt colocalizes/colocalizes_hidden_hybrid_pr.txt


python undirected_prediction_builder_distant.py degrades/degrades_hidden.txt degrades/degrades_hidden_linear.txt degrades/degrades_hidden_hybrid.txt degrades/degrades_hidden_noisy_or.txt

python prediction_combiner_labelled.py degrades/degrades_hidden_noisy_or.txt degrades/degrades_hidden_noisy_or_pr.txt

python prediction_combiner_labelled.py degrades/degrades_hidden_hybrid.txt degrades/degrades_hidden_hybrid_pr.txt


python undirected_prediction_builder_distant.py downregulates/downregulates_hidden.txt downregulates/downregulates_hidden_linear.txt downregulates/downregulates_hidden_hybrid.txt downregulates/downregulates_hidden_noisy_or.txt

python prediction_combiner_labelled.py downregulates/downregulates_hidden_noisy_or.txt downregulates/downregulates_hidden_noisy_or_pr.txt

python prediction_combiner_labelled.py downregulates/downregulates_hidden_hybrid.txt downregulates/downregulates_hidden_hybrid_pr.txt


python undirected_prediction_builder_distant.py regulates/regulates_hidden.txt regulates/regulates_hidden_linear.txt regulates/regulates_hidden_hybrid.txt regulates/regulates_hidden_noisy_or.txt

python prediction_combiner_labelled.py regulates/regulates_hidden_noisy_or.txt regulates/regulates_hidden_noisy_or_pr.txt

python prediction_combiner_labelled.py regulates/regulates_hidden_hybrid.txt regulates/regulates_hidden_hybrid_pr.txt


python undirected_prediction_builder_distant.py upregulates/upregulates_hidden.txt upregulates/upregulates_hidden_linear.txt upregulates/upregulates_hidden_hybrid.txt upregulates/upregulates_hidden_noisy_or.txt 

python prediction_combiner_labelled.py upregulates/upregulates_hidden_noisy_or.txt upregulates/upregulates_hidden_noisy_or_pr.txt

python prediction_combiner_labelled.py upregulates/upregulates_hidden_hybrid.txt upregulates/upregulates_hidden_hybrid_pr.txt

python prediction_combiner_labelled.py binds/binds_hidden_hybrid.txt colocalizes/colocalizes_hidden_hybrid.txt cleaves/cleaves_hidden_hybrid.txt degrades/degrades_hidden_hybrid.txt downregulates/downregulates_hidden_hybrid.txt upregulates/upregulates_hidden_hybrid.txt regulates/regulates_hidden_hybrid.txt combined/combined_hidden_hybrid.txt

python prediction_combiner_labelled.py binds/binds_hidden_noisy_or.txt colocalizes/colocalizes_hidden_noisy_or.txt cleaves/cleaves_hidden_noisy_or.txt degrades/degrades_hidden_noisy_or.txt downregulates/downregulates_hidden_noisy_or.txt upregulates/upregulates_hidden_noisy_or.txt regulates/regulates_hidden_noisy_or.txt combined/combined_hidden_noisy_or.txt




