python undirected_prediction_builder_distant.py binds/binds_gradients.txt binds/binds_gradients_linear.txt binds/binds_gradients_hybrid.txt binds/binds_gradients_noisy_or.txt

python prediction_combiner_labelled.py binds/binds_gradients_noisy_or.txt binds/binds_gradients_noisy_or_pr.txt

python prediction_combiner_labelled.py binds/binds_gradients_hybrid.txt binds/binds_gradients_hybrid_pr.txt


python undirected_prediction_builder_distant.py cleaves/cleaves_gradients.txt cleaves/cleaves_gradients_linear.txt cleaves/cleaves_gradients_hybrid.txt cleaves/cleaves_gradients_noisy_or.txt

python prediction_combiner_labelled.py cleaves/cleaves_gradients_noisy_or.txt cleaves/cleaves_gradients_noisy_or_pr.txt

python prediction_combiner_labelled.py cleaves/cleaves_gradients_hybrid.txt cleaves/cleaves_gradients_hybrid_pr.txt


python undirected_prediction_builder_distant.py colocalizes/colocalizes_gradients.txt colocalizes/colocalizes_gradients_linear.txt colocalizes/colocalizes_gradients_hybrid.txt colocalizes/colocalizes_gradients_noisy_or.txt

python prediction_combiner_labelled.py colocalizes/colocalizes_gradients_noisy_or.txt colocalizes/colocalizes_gradients_noisy_or_pr.txt

python prediction_combiner_labelled.py colocalizes/colocalizes_gradients_hybrid.txt colocalizes/colocalizes_gradients_hybrid_pr.txt


python undirected_prediction_builder_distant.py degrades/degrades_gradients.txt degrades/degrades_gradients_linear.txt degrades/degrades_gradients_hybrid.txt degrades/degrades_gradients_noisy_or.txt

python prediction_combiner_labelled.py degrades/degrades_gradients_noisy_or.txt degrades/degrades_gradients_noisy_or_pr.txt

python prediction_combiner_labelled.py degrades/degrades_gradients_hybrid.txt degrades/degrades_gradients_hybrid_pr.txt


python undirected_prediction_builder_distant.py downregulates/downregulates_gradients.txt downregulates/downregulates_gradients_linear.txt downregulates/downregulates_gradients_hybrid.txt downregulates/downregulates_gradients_noisy_or.txt

python prediction_combiner_labelled.py downregulates/downregulates_gradients_noisy_or.txt downregulates/downregulates_gradients_noisy_or_pr.txt

python prediction_combiner_labelled.py downregulates/downregulates_gradients_hybrid.txt downregulates/downregulates_gradients_hybrid_pr.txt


python undirected_prediction_builder_distant.py regulates/regulates_gradients.txt regulates/regulates_gradients_linear.txt regulates/regulates_gradients_hybrid.txt regulates/regulates_gradients_noisy_or.txt

python prediction_combiner_labelled.py regulates/regulates_gradients_noisy_or.txt regulates/regulates_gradients_noisy_or_pr.txt

python prediction_combiner_labelled.py regulates/regulates_gradients_hybrid.txt regulates/regulates_gradients_hybrid_pr.txt


python undirected_prediction_builder_distant.py upregulates/upregulates_gradients.txt upregulates/upregulates_gradients_linear.txt upregulates/upregulates_gradients_hybrid.txt upregulates/upregulates_gradients_noisy_or.txt 

python prediction_combiner_labelled.py upregulates/upregulates_gradients_noisy_or.txt upregulates/upregulates_gradients_noisy_or_pr.txt

python prediction_combiner_labelled.py upregulates/upregulates_gradients_hybrid.txt upregulates/upregulates_gradients_hybrid_pr.txt

python prediction_combiner_labelled.py binds/binds_gradients_hybrid.txt colocalizes/colocalizes_gradients_hybrid.txt cleaves/cleaves_gradients_hybrid.txt degrades/degrades_gradients_hybrid.txt downregulates/downregulates_gradients_hybrid.txt upregulates/upregulates_gradients_hybrid.txt regulates/regulates_gradients_hybrid.txt combined/combined_gradients_hybrid.txt


python prediction_combiner_labelled.py binds/binds_gradients_noisy_or.txt colocalizes/colocalizes_gradients_noisy_or.txt cleaves/cleaves_gradients_noisy_or.txt degrades/degrades_gradients_noisy_or.txt downregulates/downregulates_gradients_noisy_or.txt upregulates/upregulates_gradients_noisy_or.txt regulates/regulates_gradients_noisy_or.txt combined/combined_gradients_noisy_or.txt


